---
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: app
  password: ''
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: test_rails_development

test:
  <<: *default
  database: test_rails_test

production:
  <<: *default
  database: test_rails_production
